spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    passward: admin
    
server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

eureka:
  instance: 
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}